# Generated by Django 4.1.1 on 2023-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
